### ISSUE TITLE
Migrate from Realtime database

### ISSUE THREAD

**Issue by Strajk** [kiwicom/stranger-strings#12]
Real-time database is not ideal for this kind of project

**Comment by Strajk** [comment]
@D1LL1G4F pls write short explanation why

**Comment by D1LL1G4F** [comment]
Reason for sticking to Realtime database:
* too much refactoring for little (probably none) advantages
* we are not using complicated queries what is the main reason for switching
* our DB is quite small to notice any difference between scalability of Realtime DB and Firestore
* pricing of Realtime DB is based on amount of stored data (FIrestore charges for reads/writes on DB)
