### ISSUE TITLE
Translation detail: first row too wide

### ISSUE THREAD

**Issue by Strajk** [kiwicom/stranger-strings#31]
![image](https://user-images.githubusercontent.com/697301/53197319-36ec0d80-361a-11e9-9151-e052e3716133.png)

**Comment by D1LL1G4F** [comment]
Fixed in #32

**Comment by D1LL1G4F** [comment]
Fixed in master branch #33 .

**Comment by Strajk** [comment]
Merci! @D1LL1G4F
