### ISSUE TITLE
Remove `.env`, add `.env.example` instead

### ISSUE THREAD

**Issue by Strajk** [kiwicom/stranger-strings#47]
Best practice is to not add `.env` file to git (and add it to .gitignore so sb wouldn't add it by accident)

https://www.npmjs.com/package/dotenv#should-i-commit-my-env-file

Instead, provide an example in `.env.example`

Plus, there's neat tool to check if `.env` and `.env.example` matches https://github.com/codeshifu/sync-dotenv

**Comment by D1LL1G4F** [comment]
changed in #51.
